version: '3.8'

services:
  giropops-senhas:
    container_name: giropops-senhas
    image: mattlima99/linuxtips-giropops-senhas:distroless1.0
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - redis-net

  redis:
    container_name: redis
    image: redis:7.2
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge